// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var simonArray, userArray;
    $(".game-button").on("click", function(e) {
      return console.log("Clicked button" + getRandom());
    });
    simonArray = [];
    ({
      addToSimonArray: function(simonArray) {}
    });
    return userArray = [];
  });

}).call(this);
