// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var choice, clickCounter, userArray;
    userArray = [];
    clickCounter = 0;
    $(".game-button").on("click", function(e) {});
    clickCounter++;
    choice = parseInt($(this).data('index'));
    userArray.push(choice);
    console.log(userArray);
    console.log(choice);
    return console.log(clickCounter);
  });

}).call(this);
